// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjaowwmsacyvefrvwyof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqYW93d21zYWN5dmVmcnZ3eW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjM4MDUsImV4cCI6MjA2NjY5OTgwNX0.IBa57ArMm-JdETswIFJNtDaaHaBz0wcroU80QblgiDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);